# Generated by Django 5.1.4 on 2025-01-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
